### ISSUE TITLE
bottom thickness too large

### ISSUE THREAD

**Issue by stunback** [rhett-chen/grasp-auto-annotation#1]
https://github.com/rhett-chen/grasp-auto-annotation/blob/64bd1b9356b1c8094548e6da12ebd0b1401ed4b5/auto_annotation/generate_object_grasp_label_v2.py#LL125C15-L125C15
```
    bottom_thickness = 0.1
```
这个尾部thickness应该是0.01吧，0.1太厚了

**Comment by huamo555** [comment]
> https://github.com/rhett-chen/grasp-auto-annotation/blob/64bd1b9356b1c8094548e6da12ebd0b1401ed4b5/auto_annotation/generate_object_grasp_label_v2.py#LL125C15-L125C15
> 
> ```
>     bottom_thickness = 0.1
> ```
> 
> 这个尾部thickness应该是0.01吧，0.1太厚了

您好，请问您在生成标签后有尝试可视化抓取标签吗？
